name: mdsine2
channels:
  - default
  - anaconda
  - conda-forge
  - etetoolkit
dependencies:
  - python=3.7.3
  - ete3
  - ete_toolchain
  - pip
  - pip:
    - git+git://github.com/gerberlab/MDSINE2@master
